## Summary

A quick demonstration of how the optimisation using the Genetic Algorithm (GA) as implemented in *darwpy* works. 

Steps:

1. Use get_problems() to load all the optimisation problems as in darwpy.problems
2. Use **GA** to get the solution
3. Visualise the best solution in 2D and 3D*

*Note that all the optimsiation functions have two parameters, hence it is possible to visualise in 3D

In the last part of the notebook, it is shown how the same problems can be solved with yabox 

In [23]:
import darwpy as dp

In [21]:
## optional (requires jupyter lab version 3 and ipyml installed) to enable interactive features of matplotlib
## see https://github.com/matplotlib/ipympl#installation for details on installation
## 
%matplotlib widget

In [70]:
import numpy as np

def get_domain(bounds=[-5.12,5.12],dimensions=2):    
    out = {}
    for i in range(dimensions):
        m1,m2 = bounds
        out[i] = {'min':m1,'max':m2,'init':np.random.randint(m1,m2),'min0':m1,'max0':m2}
    return out


domain = get_domain()

def cost_func(sol):
    return sum(s**2 for s in sol)
    
pop1,fitness1,slope1 = dp.GA(domain,cost_func,N=60,generations=2000)


  2%|▏         | 38/2000 [00:00<00:09, 197.57it/s]

Best initial fitness: 20.0
pop@0 [gen,fitness]: ['0->[0.0, 4.10541748029737]', '1->[0.0, 4.197407323985651]', '5->[0.0, 11.758336734270951]', '10->[0.0, 17.686895868682925]', '20->[0.0, 20.0]']


 27%|██▋       | 547/2000 [00:02<00:05, 248.34it/s]

pop@500 [gen,fitness]: ['0->[422.0, 1.133058736539354e-05]', '1->[423.0, 1.133058736539354e-05]', '5->[423.0, 1.133058736539354e-05]', '10->[500.0, 1.133058736539354e-05]', '20->[500.0, 1.133058736539354e-05]']


 52%|█████▏    | 1045/2000 [00:04<00:03, 253.75it/s]

pop@1000 [gen,fitness]: ['0->[422.0, 1.133058736539354e-05]', '1->[423.0, 1.133058736539354e-05]', '5->[423.0, 1.133058736539354e-05]', '10->[1000.0, 1.133058736539354e-05]', '20->[1000.0, 1.133058736539354e-05]']


 77%|███████▋  | 1544/2000 [00:06<00:01, 255.27it/s]

pop@1500 [gen,fitness]: ['0->[422.0, 1.133058736539354e-05]', '1->[423.0, 1.133058736539354e-05]', '5->[423.0, 1.133058736539354e-05]', '10->[1500.0, 1.133058736539354e-05]', '20->[1500.0, 1.133058736539354e-05]']


100%|██████████| 2000/2000 [00:08<00:00, 246.41it/s]



Best fitness 1.5871319293861365e-08
best sol: [ 7.70074056e-05 -9.97054601e-05] obtained in generation 1662.0
The slope from 1000 to end was -1.5167826051999867e-08
[ 7.70074056e-05 -9.97054601e-05  1.66200000e+03  1.58713193e-08]


In [76]:
print(pop1[0,len(domain):])

[1.66200000e+03 1.58713193e-08]


In [32]:
## Load the availabe problems
obj_funcs = dp.get_problems()

print("The available functions to try GA are: \n- {}".format('\n- '.join(obj_funcs.keys())))

The available functions to try GA are: 
- Ackley
- BaseProblem
- CrossInTray
- DixonPrice
- Easom
- EggHolder
- Griewank
- HolderTable
- Levy
- Michalewicz
- Rastrigin
- Rosenbrock
- Schwefel
- StyblinskiTang


In [17]:
## Select one problem
bfunc = obj_funcs['EggHolder']()

In [33]:
## Run GA
pop,fitness,slope = dp.GA(bfunc.domain,bfunc.evaluate,N=60,generations=2000)

  1%|          | 14/2000 [00:00<00:14, 137.64it/s]

Best initial fitness: 232.55284528681176
pop@0 [gen,fitness]: ['0->[0.0, -446.53361655833464]', '1->[0.0, -428.03462953759254]', '5->[0.0, -113.00262389831505]', '10->[0.0, 31.519462479944636]', '20->[0.0, 232.55284528681176]']


 27%|██▋       | 540/2000 [00:02<00:07, 200.01it/s]

pop@500 [gen,fitness]: ['0->[336.0, -934.2396434127779]', '1->[337.0, -934.2396434127779]', '5->[337.0, -934.2396434127779]', '10->[500.0, -934.2396434127779]', '20->[500.0, -934.2396434127779]']


 52%|█████▏    | 1039/2000 [00:05<00:04, 213.31it/s]

pop@1000 [gen,fitness]: ['0->[984.0, -955.6293709207914]', '1->[985.0, -955.6293709207914]', '5->[985.0, -955.6293709207914]', '10->[1000.0, -955.6293709207914]', '20->[1000.0, -955.6293709207914]']


 77%|███████▋  | 1535/2000 [00:07<00:02, 218.38it/s]

pop@1500 [gen,fitness]: ['0->[1113.0, -959.3238659137021]', '1->[1114.0, -959.3238659137021]', '5->[1114.0, -959.3238659137021]', '10->[1500.0, -959.3238659137021]', '20->[1500.0, -959.3238659137021]']


  1%|          | 19/2000 [00:00<00:10, 184.16it/s]



Best fitness -959.3238659137021
best sol: [511.9077379  404.09741637] obtained in generation 1113.0
The slope from 1000 to end was -0.0016433003036653558
** Initial pop was provided by user
Best initial fitness: -959.3238659137021
pop@0 [gen,fitness]: ['0->[0.0, -959.3238659137021]', '1->[0.0, -959.3238659137021]', '5->[0.0, -959.3238659137021]', '10->[0.0, -959.3238659137021]', '20->[0.0, -959.3238659137021]']


 27%|██▋       | 542/2000 [00:02<00:06, 213.99it/s]

pop@500 [gen,fitness]: ['0->[0.0, -959.3238659137021]', '1->[0.0, -959.3238659137021]', '5->[0.0, -959.3238659137021]', '10->[500.0, -959.3238659137021]', '20->[500.0, -959.3238659137021]']


 52%|█████▏    | 1031/2000 [00:04<00:04, 212.24it/s]

pop@1000 [gen,fitness]: ['0->[780.0, -959.5058586516491]', '1->[781.0, -959.5058586516491]', '5->[781.0, -959.5058586516491]', '10->[1000.0, -959.5058586516491]', '20->[1000.0, -959.5058586516491]']


 77%|███████▋  | 1532/2000 [00:07<00:02, 215.01it/s]

pop@1500 [gen,fitness]: ['0->[780.0, -959.5058586516491]', '1->[781.0, -959.5058586516491]', '5->[781.0, -959.5058586516491]', '10->[1500.0, -959.5058586516491]', '20->[1500.0, -959.5058586516491]']


100%|██████████| 2000/2000 [00:09<00:00, 211.00it/s]



Best fitness -959.5164979600016
best sol: [511.96373105 404.1673975 ] obtained in generation 1604.0
The slope from 1000 to end was -1.5629343659767075e-05


In [34]:
## Visualise best solution in 2D
bfunc.plot2d(sol=pop[0])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(<Figure size 1200x800 with 1 Axes>, <AxesSubplot:>)

In [35]:
## Visualise best solution in 2D
bfunc.plot3d(sol=pop[0])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 511.96373105  404.1673975  1604.         -959.51649796]


## Try the same optimisation using yabox 

[ensure it is installed first]

In [39]:
import yabox

In [56]:
class Problem(object):
    """Prepare a yabox compatible object """

    def __init__(self, fitness_func, dim=None, bounds=None, default_bounds=(-1, 1), name=None):
        if bounds is None:
            bounds = [default_bounds]
            if dim is not None:
                bounds = [default_bounds] * dim
        self.dimensions = len(bounds)
        self.bounds = bounds
        self.name = name or self.__class__.__name__
        self.fitness_func = fitness_func

    def evaluate(self,sol):
        return self.fitness_func(sol)

    def __call__(self, *args, **kwargs):
        return self.evaluate(*args, **kwargs)

    def __repr__(self):
        return '{} {}D'.format(self.name, self.dimensions)

In [60]:
bfunc2 = obj_funcs['Ackley']()

pr = Problem(bfunc2.evaluate, dim=bfunc2.dimensions, bounds=bfunc2.bounds)
de = yabox.DE(pr, pr.bounds, maxiters=5000)
sol2 = de.solve(show_progress=True)
print(sol2)

Optimizing (DE): 50000it [00:06, 7754.38it/s]                         

(array([[0., 0.],
       [0., 0.]]), 4.440892098500626e-16)


In [62]:
bfunc2.plot3d(sol=sol2[0][0])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …